function(re_enable_sanitizers target)
  if(RE_ENABLE_TSAN AND (RE_ENABLE_ASAN OR RE_ENABLE_UBSAN))
    message(FATAL_ERROR "TSan cannot be combined with ASan/UBSan in this project")
  endif()

  if(MSVC)
    if(RE_ENABLE_ASAN)
      target_compile_options(${target} PRIVATE /fsanitize=address)
      target_link_options(${target} PRIVATE /fsanitize=address)
    endif()
    return()
  endif()

  set(sanitizers "")
  if(RE_ENABLE_ASAN)
    list(APPEND sanitizers "address")
  endif()
  if(RE_ENABLE_UBSAN)
    list(APPEND sanitizers "undefined")
  endif()
  if(RE_ENABLE_TSAN)
    list(APPEND sanitizers "thread")
  endif()

  if(sanitizers)
    list(JOIN sanitizers "," sanitizer_flags)
    target_compile_options(${target} PRIVATE -fsanitize=${sanitizer_flags} -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=${sanitizer_flags})
  endif()
endfunction()
